access_key = ""
secret_key = ""
key_name = "alexTERRA2"
key_full_path = "~/Desktop/aws/tf/test/DMCFrontEnd/alexTERRA2.pem"
activeMqRootPass = "admin1"
activeMqUserPass = "user1"
stackPrefix = "alexPROD"